-- ========= Limpeza =========
--deletar insumos utilizados
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE InsumosUtilizados CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
-- deletar cultura
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Cultura CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
--deletar insumos
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Insumos CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
-- deletar fornecedores
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Fornecedores CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
-- ========================== Criação das Tabelas ==========================

CREATE TABLE Fornecedores (
    id_fornecedor       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR2(100) NOT NULL,
    data_cadastro       DATE DEFAULT SYSDATE
);


CREATE TABLE Insumos (
    id_insumo           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_fornecedor       NUMBER(10) NOT NULL,
    nome                VARCHAR2(255) NOT NULL,
    tipo                VARCHAR2(50) NOT NULL, -- 'Produto' ou 'Serviço'
    quantidade_estoque  NUMBER, -- Só aplicável a produtos
    custo_unitario      NUMBER,
    data_validade       DATE, -- Só aplicável a produtos
    data_cadastro       DATE DEFAULT SYSDATE
);

CREATE TABLE Cultura (
    id_culturas             NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_ha               NUMBER(10) NOT NULL,
    nome                    VARCHAR2(100) NOT NULL,
    data_cadastro       DATE DEFAULT SYSDATE
);

CREATE TABLE InsumosUtilizados (
    id_insumo_utilizado     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cultura              NUMBER(10) NOT NULL,
    id_insumo               NUMBER(10) NOT NULL,
    quantidade_utilizada    NUMBER(10),
    data_cadastro       DATE DEFAULT SYSDATE
);





-- ================== Definição das Chaves Estrangeiras (FK) =================
ALTER TABLE Insumos
ADD CONSTRAINT fk_insumos_fornecedor
FOREIGN KEY (id_fornecedor)
REFERENCES Fornecedores(id_fornecedor);

ALTER TABLE InsumosUtilizados
ADD CONSTRAINT fk_utilizados_insumo
FOREIGN KEY (id_insumo) REFERENCES Insumos(id_insumo);

ALTER TABLE InsumosUtilizados
ADD CONSTRAINT fk_utilizados_cultura
FOREIGN KEY (id_cultura) REFERENCES Cultura(id_culturas);
 

-- inserção dados fornecedor
insert into Fornecedores (nome) values ('Yara Brasil S/A');
insert into Fornecedores (nome) values ('Nutrien Soluções Agrícolas');
insert into Fornecedores (nome) values ('Mosaic Fertilizantes');
insert into Fornecedores (nome) values ('PhosAgro');


-- inserção dados Cultura
insert into Cultura (area_ha, nome) values (100, 'Milho');
insert into Cultura (area_ha, nome) values (200, 'Café');

-- inserção dados Insumos
insert into Insumos (id_fornecedor, nome, tipo, quantidade_estoque, custo_unitario, data_validade) values (1, 'Fertilizante orgânico', 'Fertilizante', 100, 250.30, TO_DATE('2026-03-01', 'YYYY-MM-DD'));
insert into Insumos (id_fornecedor, nome, tipo, quantidade_estoque, custo_unitario, data_validade) values (2, 'Fertilizante mineral', 'Fertilizante', 70, 230.30, TO_DATE('2026-05-01', 'YYYY-MM-DD'));
insert into Insumos (id_fornecedor, nome, tipo, quantidade_estoque, custo_unitario, data_validade) values (3, 'Biofertilizante', 'Fertilizante', 90, 270.30, TO_DATE('2026-10-01', 'YYYY-MM-DD'));
insert into Insumos (id_fornecedor, nome, tipo, quantidade_estoque, custo_unitario, data_validade) values (4, 'Fertilizante organomineral.', 'Fertilizante', 50, 280.30, TO_DATE('2026-01-01', 'YYYY-MM-DD'));

-- inserção dados Insumos utilizados
insert into InsumosUtilizados (id_cultura, id_insumo, quantidade_utilizada) values (1, 1, 5);
insert into InsumosUtilizados (id_cultura, id_insumo, quantidade_utilizada) values (2, 2, 10);
insert into InsumosUtilizados (id_cultura, id_insumo, quantidade_utilizada) values (1, 3, 9);
insert into InsumosUtilizados (id_cultura, id_insumo, quantidade_utilizada) values (2, 4, 20);

