-- ========= Limpeza =========
--deletar insumos utilizados
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE InsumosUtilizados CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
-- deletar cultura
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Cultura CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
--deletar insumos
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Insumos CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
-- deletar fornecedores
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Fornecedores CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
-- ========================== Criação das Tabelas ==========================

CREATE TABLE Fornecedores (
    id_fornecedor       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR2(100) NOT NULL,
    data_cadastro       DATE DEFAULT SYSDATE
);


CREATE TABLE Insumos (
    id_insumo           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_fornecedor       NUMBER(10) NOT NULL,
    nome                VARCHAR2(255) NOT NULL,
    tipo                VARCHAR2(50) NOT NULL, -- 'Produto' ou 'Serviço'
    quantidade_estoque  NUMBER, -- Só aplicável a produtos
    custo_unitario      NUMBER,
    data_validade       DATE, -- Só aplicável a produtos
    data_cadastro       DATE DEFAULT SYSDATE
);

CREATE TABLE Cultura (
    id_culturas             NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_ha               NUMBER(10) NOT NULL,
    nome                    VARCHAR2(100) NOT NULL,
    data_cadastro       DATE DEFAULT SYSDATE
);

CREATE TABLE InsumosUtilizados (
    id_insumo_utilizado     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cultura              NUMBER(10) NOT NULL,
    id_insumo               NUMBER(10) NOT NULL,
    quantidade_utilizada    NUMBER(10),
    data_cadastro       DATE DEFAULT SYSDATE
);





-- ================== Definição das Chaves Estrangeiras (FK) =================
ALTER TABLE Insumos
ADD CONSTRAINT fk_insumos_fornecedor
FOREIGN KEY (id_fornecedor)
REFERENCES Fornecedores(id_fornecedor);

ALTER TABLE InsumosUtilizados
ADD CONSTRAINT fk_utilizados_insumo
FOREIGN KEY (id_insumo) REFERENCES Insumos(id_insumo);

ALTER TABLE InsumosUtilizados
ADD CONSTRAINT fk_utilizados_cultura
